import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler";
import { AnimatedLanguageSwitcher } from "@/components/ui/animated-language-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* Fixed position controls in bottom right */}
        <div className="fixed bottom-4 right-4 z-50 flex flex-row gap-4 items-center">
          <AnimatedThemeToggler className="cursor-pointer" />
          <AnimatedLanguageSwitcher className="cursor-pointer" />
        </div>
      </body>
    </html>
  );
}